package com.paysync.gateway.data.security

import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Encrypts one settings value with AES-256-GCM (pure JVM, unit-testable).
 *
 * Wire format of a stored value: `"v1:" + base64(ivLen ‖ iv ‖ ciphertext+tag)`.
 * The plaintext is a one-char type tag followed by the payload, so every
 * SharedPreferences type round-trips exactly:
 *  `s` String · `l` Long · `i` Int · `b` Boolean ("1"/"0") · `f` Float (raw
 *  bits) · `S` Set<String> (JSON array).
 *
 * The preference KEY is bound as GCM associated data: a ciphertext copied
 * from one key to another (e.g. the URL value pasted over the secret) fails
 * authentication instead of decrypting. The IV is generated by the cipher
 * itself (required by the Android Keystore, which forbids caller IVs).
 *
 * [decrypt] never throws: tampered, truncated, foreign-key or undecryptable
 * values return null and the caller falls back to the default.
 */
class AesGcmValueCodec(private val keyProvider: () -> SecretKey) {

    private val gson = Gson()
    private val setType = object : TypeToken<List<String>>() {}.type

    fun encrypt(prefKey: String, value: Any): String {
        val plain = serialize(value).toByteArray(Charsets.UTF_8)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, keyProvider())
        cipher.updateAAD(aad(prefKey))
        val ct = cipher.doFinal(plain)
        val iv = cipher.iv
        require(iv != null && iv.size in 1..255) { "cipher produced no usable IV" }
        val out = ByteArray(1 + iv.size + ct.size)
        out[0] = iv.size.toByte()
        System.arraycopy(iv, 0, out, 1, iv.size)
        System.arraycopy(ct, 0, out, 1 + iv.size, ct.size)
        return PREFIX + Base64.getEncoder().encodeToString(out)
    }

    fun decrypt(prefKey: String, stored: String): Any? = try {
        if (!stored.startsWith(PREFIX)) {
            null
        } else {
            val raw = Base64.getDecoder().decode(stored.substring(PREFIX.length))
            val ivLen = raw[0].toInt() and 0xFF
            if (ivLen == 0 || raw.size <= 1 + ivLen) {
                null
            } else {
                val cipher = Cipher.getInstance(TRANSFORMATION)
                cipher.init(
                    Cipher.DECRYPT_MODE, keyProvider(),
                    GCMParameterSpec(TAG_BITS, raw, 1, ivLen)
                )
                cipher.updateAAD(aad(prefKey))
                val plain = cipher.doFinal(raw, 1 + ivLen, raw.size - 1 - ivLen)
                deserialize(String(plain, Charsets.UTF_8))
            }
        }
    } catch (_: Exception) {
        null
    }

    private fun serialize(value: Any): String = when (value) {
        is String -> "s$value"
        is Long -> "l$value"
        is Int -> "i$value"
        is Boolean -> if (value) "b1" else "b0"
        is Float -> "f${value.toRawBits()}"
        is Set<*> -> "S" + gson.toJson(value.map { it as String })
        else -> throw IllegalArgumentException("Unsupported settings type: ${value.javaClass.name}")
    }

    private fun deserialize(s: String): Any? {
        if (s.isEmpty()) return null
        val payload = s.substring(1)
        return when (s[0]) {
            's' -> payload
            'l' -> payload.toLong()
            'i' -> payload.toInt()
            'b' -> payload == "1"
            'f' -> Float.fromBits(payload.toInt())
            'S' -> HashSet<String>(gson.fromJson<List<String>>(payload, setType) ?: emptyList())
            else -> null
        }
    }

    private fun aad(prefKey: String): ByteArray = (AAD_PREFIX + prefKey).toByteArray(Charsets.UTF_8)

    companion object {
        const val PREFIX = "v1:"
        private const val AAD_PREFIX = "paysync-settings-v1:"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val TAG_BITS = 128
    }
}
